#!/bin/bash

WEB_HOST=172.17.1.218
NTP_HOST=172.17.1.214
DNS_HOST=172.17.1.222
CHEF_HOST=172.17.1.217
KIBANA_HOST=172.17.1.221

# Web-API
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 3000 -j DNAT --to-destination $WEB_HOST:3000
iptables -A FORWARD -p tcp -d $WEB_HOST --dport 3000 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# CHEF-API
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 4646 -j DNAT --to-destination $CHEF_HOST:4646
iptables -A FORWARD -p tcp -d $CHEF_HOST --dport 4646 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# KIBANA-API
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 5601 -j DNAT --to-destination $KIBANA_HOST:5601
iptables -A FORWARD -p tcp -d $KIBANA_HOST --dport 5601 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# NTP_HOST
iptables -t nat -A PREROUTING -p udp -i eth0 --dport 123 -j DNAT --to-destination $NTP_HOST:123
#iptables -t nat -A PREROUTING -i eth0 -d $NTP_HOST -p udp --dport 123 -j REDIRECT --to-ports 123
iptables -A FORWARD -p udp -d $NTP_HOST --dport 123 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# DNS_HOST
iptables -t nat -A PREROUTING -p udp -i eth0 --dport 53 -j DNAT --to-destination $DNS_HOST:53
#iptables -t nat -A PREROUTING -i eth0 -d $DNS_HOST -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -A FORWARD -p udp -d $DNS_HOST --dport 53 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# Masquerage it
iptables -t nat -A POSTROUTING -j MASQUERADE

while true; do
    sleep 300
done
