FROM digitalrebar/base
MAINTAINER Victor Lowther <victor@rackn.com>

RUN echo ${DR_TAG}
ARG DR_TAG
RUN echo ${DR_TAG}

ADD http://localhost:28569/${DR_TAG}/linux/amd64/sign-it /usr/local/bin/
RUN chmod 755 /usr/local/bin/*

COPY entrypoint.d/*.sh /usr/local/entrypoint.d/

