#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/heartbeat_command'
require 'delayed/heartbeat/plugin'
require 'delayed/heartbeat/worker_model'
Delayed::HeartbeatCommand.new(ARGV).daemonize
