#!/bin/bash

consul agent --join consul --config-dir /etc/consul.d --data-dir /data &

answer=""
# We need consul to converge on a leader.
# This can take a little time, so we ask for
# leader status.  The leader status returns
# nothing, a string that says no leader, or
# the leader IP:port pair.  The default port
# is 8300 for server communication.
while [[ $answer != *:8300* ]]; do
  sleep 1
  answer=`curl http://localhost:8500/v1/status/leader`
  echo "Waiting for consul leader: $answer"
done

IP=$(ip a s eth0|grep 'inet '|egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}')

sed -i "s/^server: .*$/server: ${IP}/" /etc/cobbler/settings
sed -i "s/^next_server: .*$/next_server: ${IP}/" /etc/cobbler/settings

make-ssl-cert generate-default-snakeoil --force-overwrite

/etc/init.d/tftpd-hpa start
/etc/init.d/cobbler start
/etc/init.d/apache2 start

cobbler get-loaders
cobbler sync

echo "Web user: cobbler"
echo "Web pass: <empty>"

while true; do
  sleep 60
done

