#!/usr/bin/env bash
# Copyright 2015, RackN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Run digitalrebar in a docker container.
# $1 = OS to run in
# $@ = Command to run, if nothing then /bin/bash -i

if [[ $0 = /* ]]; then
    mountdir="$0"
elif [[ $0 = .*  || $0 = */* ]]; then
    mountdir="$(readlink "$PWD/$0")"
    if [ "$mountdir" == "" ] ; then
        mountdir="$PWD/$0"
    fi
else
    echo "Cannot figure out where core is!"
    exit 1
fi

# This gets us to core
mountdir="${mountdir%/tools/docker-admin}"
# This gets us to the parent directory of core, where presumably the rest of our repos are checked out
mountdir="${mountdir%/*}"

. "$mountdir/core/tools/da-lib.sh"

# We always want a provisioner and a forwarder
docker_admin_default_containers

bring_up_admin_containers

echo "Bringing containers up.  Exiting the shell will kill and remove the containers"
export PS1="(docker-compose) $PS1"
export REBAR_ENDPOINT="https://127.0.0.1"
export REBAR_KEY="rebar:rebar1"
/bin/bash -i
tear_down_admin_containers
