#!/bin/bash
# chkconfig:         2345 90 10
# description:       Service runner for Crowbar
### BEGIN INIT INFO
# Provides:          opencrowbar-webserver
# Required-Start:    $syslog $network $named postrgesql-9.3
# Required-Stop:     $syslog $network $named postgresql-9.3
# Should-Start:      xinetd
# Should-Stop:       xinetd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the OpenCrowbar Web application
# Description:       Manages the OpenCrowbar Web application
### END INIT INFO

PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
GEMFILE_LOCK=/opt/opencrowbar/core/rails/Gemfile.lock

# if we started in development, make sure we're running development
if [[ -f /tmp/development.txt ]]; then
    RAILS_ENV=development
else
    [[ $RAILS_ENV ]] || RAILS_ENV=production
fi

export RAILS_ENV
if [[ -f /etc/redhat-release || -f /etc/centos-release ]]; then
    OS=redhat
elif [[ -d /etc/apt ]]; then
    OS=ubuntu
elif [[ -f /etc/SuSE-release ]]; then
    OS=suse
fi

case $RAILS_ENV in
    development) PUMA_CFG="puma-dev.cfg";;
    production)  PUMA_CFG="puma.cfg";;
    test)        PUMA_CFG="puma-test.cfg";;
esac


if [[ -f /etc/crowbar.install.key ]]; then
    read CROWBAR_KEY < /etc/crowbar.install.key
    export CROWBAR_KEY
fi

as_crowbar() (
    su -l -c "cd /opt/opencrowbar/core/rails; RAILS_ENV=$RAILS_ENV $*" crowbar
)

que_worker() {
    queue="$1"
    shift
    workers="$1"
    shift
    for ((i=0; i < workers; i++)) ; do
        cmd="QUE_WORKER_COUNT=1 QUE_QUEUE=$queue bundle exec rake que:work"
        as_crowbar "$cmd" </dev/zero &>> "/var/log/crowbar/$queue.$i.log" &
    done
}

start_workers() {
    que_worker NodeRoleRunner 10
    que_worker HighPriorityRunner 2
    disown -a
}

stop_workers() {
    pkill -f que:work
    COUNT=0
    while pgrep -l -f que:work 2>&1 >/dev/null ;
    do
        sleep 1
        COUNT=`expr $COUNT + 1`
        if [[ $COUNT -gt 30 ]] ;
        then
            pkill -9 -f que:work
        fi
    done
}

status_workers() {
    pgrep -l -f que:work
}

start(){
    if status; then
        echo "Crowbar is already running"
        return 1
    fi
    rm /opt/opencrowbar/core/rails/tmp/pids/*
    if [[ $OS = suse ]]; then
        # refresh the Gemfile.lock content before starting the server
        # (outdated file can cause problems after any of the required
        # rubygems were updated)
        rm -f $GEMFILE_LOCK
        as_crowbar bundle install --local --quiet
    fi
    as_crowbar bundle exec puma -d -C $PUMA_CFG
    start_workers
}

stop() {
    as_crowbar bundle exec pumactl -F $PUMA_CFG stop
    stop_workers
}

restart() {
    stop; start
}

status() {
    as_crowbar bundle exec pumactl -F $PUMA_CFG status && status_workers
}

mkdir -p /var/run/crowbar && chown crowbar:crowbar /var/run/crowbar

case "$1" in
    start) start;;
    stop) stop;;
    status) status;;
    restart) restart;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
