FROM digitalrebar/deploy-service-wrapper
MAINTAINER Victor Lowther <victor@rackn.com>

ENV SERVICE_NAME provisioner
ENV TFTPROOT /tftpboot
ENV WEBPORT 8091
ENV APIPORT 8092

ARG DR_TAG
# Get packages
ADD http://localhost:28569/${DR_TAG}/linux/amd64/provisioner-mgmt /usr/local/bin/
ADD http://localhost:28569/${DR_TAG}/linux/amd64/sign-it /usr/local/bin/
ADD https://s3-us-west-2.amazonaws.com/rebar-sws/sws-linux-amd64 /usr/local/bin/sws
ADD https://s3-us-west-2.amazonaws.com/rackn-busybox/busybox /tmp/busybox
ADD http://downloads.sourceforge.net/project/elilo/elilo/elilo-3.16/elilo-3.16-all.tar.gz /tmp/elilo.tar.gz
ADD  https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz /tmp/syslinux-6.03.tar.xz
# for esxi
ADD https://www.kernel.org/pub/linux/utils/boot/syslinux/3.xx/syslinux-3.86.tar.xz /tmp/syslinux-3.86.tar.xz
ADD http://boot.ipxe.org/ipxe.efi /tmp/ipxe.efi
ADD  http://boot.ipxe.org/ipxe.pxe /tmp/ipxe.pxe
COPY entrypoint.d/*.sh /usr/local/entrypoint.d/
COPY start-up.sh udhcpc_config stage1_init /tmp/
COPY explode_iso.sh /

COPY update-nodes/templates/ /opt/provisioner-mgmt/templates
COPY update-nodes/bootenvs/ /opt/provisioner-mgmt/bootenvs

RUN chmod 755 /usr/local/bin/*

# Set our command
ENTRYPOINT ["/sbin/docker-entrypoint.sh"]git 

# Get Latest Go
RUN apt-get -y update && apt-get -y install bsdtar createrepo xz-utils unzip bsdmainutils
RUN apt-get -y purge make build-essential
