#!/bin/ash
export PATH=/bin
echo "In Busybox"
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs dev /dev
mount -t tmpfs root /newinitramfs
mkdir /dev/pts
mount -t devpts devpts /dev/pts
xz -d -c -f lib.cpio.xz |cpio -id
touch /dev/mdev.log /dev/mdev.seq
echo '$MODALIAS=.* 0:0 660 @/bin/modprobe "$MODALIAS"' >/etc/mdev.conf
echo /bin/mdev >/proc/sys/kernel/hotplug
mdev -s
# Load devices not loaded by mdev -s
for i in /sys/class/net/*/uevent; do
    printf 'add' > "$i"; 
done 2>/dev/null; 
unset i
for i in /sys/bus/usb/devices/*; do
    case "${i##*/}" in
        [0-9]*-[0-9]*)
	    printf 'add' > "$i/uevent";;
    esac
done; unset i
# Load kernel modules, run twice.
find /sys -name 'modalias' -type f -exec cat '{}' + | sort -u | xargs -n 1 modprobe  2>/dev/null
find /sys -name 'modalias' -type f -exec cat '{}' + | sort -u | xargs -n 1 modprobe  2>/dev/null
bootif=$(grep -o 'BOOTIF=[^ ]*' /proc/cmdline)
nextone=$(grep -o 'stage2=[^ ]*' /proc/cmdline)
if test -z "$bootif"; then
    echo "Missing required parameter BOOTIF"
fi

if test -z "$nextone"; then
    echo "Missing required parameter stage2"
fi

if test -z "$bootif" || test -z "$nextone"; then
    sleep 99999
    exit 1
fi

bootif=${bootif#*01-}
bootif=${bootif//-/:}
nextone=${nextone#*=}

pxedev=""
for dev in /sys/class/net/*; do
    test -f "$dev/address" || continue
    if test "$(cat "$dev/address")" = "$bootif"; then
        pxedev=${dev##*/}
        break
    fi
done
if test -z "$pxedev"; then
    echo "Failed to find network device we booted from"
    echo "This should never happen"
    exit 1
fi
echo "Configuring boot interface"
ip link set "$pxedev" up
udhcpc -R -a -i "$pxedev"
echo "Fetching second-stage initramfs"
(cd /tmp; wget "$nextone")
(cd /newinitramfs; xz -c -d -f /tmp/"${nextone##*/}" |cpio -id)
echo "Switching to second-stage initramfs"
for fs in /dev /dev/pts /proc /sys; do
    mount --bind "$fs" "/newinitramfs$fs"
done
echo /sbin/hotplug >/proc/sys/kernel/hotplug
pkill udhcpc
exec switch_root /newinitramfs /init
echo "This should never happen!"
sleep 9999999
