FROM digitalrebar/deploy-service-wrapper
MAINTAINER Victor Lowther <victor@rackn.com>

ARG DR_TAG
# Set our command
ENTRYPOINT ["/sbin/docker-entrypoint.sh"]

# Get packages
RUN apt-get update \
    && apt-get -y --no-install-recommends install make build-essential cpanminus perl perl-doc libdbd-pg-perl \
      curl coreutils postgresql-client \
    && cpanm --quiet --notest App::Sqitch \
    && mkdir -p /etc/goiardi /var/cache/goiardi \
    && apt-get -y purge make build-essential \
    && curl -fgL -o '/tmp/chef.deb' \
      'https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_11.18.12-1_amd64.deb' \
    && dpkg -i /tmp/chef.deb && rm -f /tmp/chef.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /root/.cpanm

ADD https://github.com/ctdk/goiardi/releases/download/v0.11.0/goiardi-0.11.0-linux-amd64 /usr/local/bin/goiardi
ADD https://github.com/ctdk/goiardi/archive/v0.11.0.tar.gz /tmp/goiardi.tar.gz
RUN chmod 755 /usr/local/bin/goiardi \
    && cd /tmp \
    && tar xf goiardi.tar.gz \
    && mv goiardi*/sql-files/postgres-bundle . \
    && rm -rf goiardi*

COPY goiardi.conf /tmp
COPY entrypoint.d/*.sh /usr/local/entrypoint.d/

