FROM ubuntu:14.04
MAINTAINER Victor Lowther <victor@rackn.com>

ENV GOPATH /go

ARG DR_TAG

# Get packages
RUN mkdir -p /usr/local/sbin/ /usr/local/entrypoint.d /etc/rebar-data && \
    apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -y curl unzip git jq build-essential && \
    curl -fgL -o '/tmp/goball.tgz' \
         'https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz' && \
    tar -C '/usr/local' -zxf /tmp/goball.tgz && rm /tmp/goball.tgz
ADD http://localhost:28569/${DR_TAG}/linux/amd64/rebar /usr/local/bin/rebar
COPY docker-entrypoint.sh /sbin/docker-entrypoint.sh
RUN chmod 755 /usr/local/bin/rebar
