#!/bin/bash

set -x

[[ -f /etc/init.d/crowbar ]] || \
    cp etc/init.d/crowbar /etc/init.d/crowbar

if which chkconfig; then
    chkconfig crowbar on
else
    for i in 2 3 4 5; do
        [[ -d /etc/rc$i.d ]] || continue
        ln -sf /etc/init.d/crowbar "/etc/rc$i.d/S99crowbar"
    done
fi

/etc/init.d/crowbar start
# Wait for the webserver to be ready.
while ! crowbar -U crowbar -P crowbar -E http://127.0.0.1:3000 ping; do
    sleep 1
done
