#!/bin/bash

## only do this on real installs.
[[  -d /opt/opencrowbar/core ]] || \
    { echo "Not an admin node, not installing Crowbar"; exit 0; }

set -x

cd /opt/opencrowbar/core/rails
tasks=("rake test"
       "rspec")

for task in "${tasks[@]}"; do
    su -l -s /bin/bash -c "cd /opt/opencrowbar/core/rails; RAILS_ENV=$RAILS_ENV bundle exec $task" crowbar && continue
    echo "Task $task failed." >&2
    # GREG: Put this back one day: exit 1
done

