#!/bin/bash
NODE_DIR="$HOME/.cache/digitalrebar/tftpboot/nodes/$1"
init="$NODE_DIR/rebar-init"
echo "Waiting for $1 to be launchable"
while [[ ! -x $init ]]; do
    printf '%s' "."
    sleep 1
done
sudo "$init"
